import type { Metadata } from "next";
import './globals.css';
import AuthProvider from "@/context/authProvider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "beketikro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`antialiased`}
        >
          {children}
        <ToastContainer/>
        </body>
      </AuthProvider>
    </html>
  );
}
